name: deploy_b

on:
  push:

  workflow_dispatch :

jobs:

  deploy:
    permissions:
     contents: 'read'
     id-token: 'write'
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate using Workload Identity Federation
      if : False 
      uses: google-github-actions/auth@v2
      with:
        export_environment_variables: true
        create_credentials_file : true 
        # workload_identity_provider: projects/743056286656/locations/global/workloadIdentityPools/undp-test-earth-engine-pool-id/providers/pool-id
        workload_identity_provider: projects/743056286656/locations/global/workloadIdentityPools/pool-id-3/providers/provider-id-3
        service_account: undp-test-earth-engine@undp-test-earth-engine.iam.gserviceaccount.com
        project_id: undp-test-earth-engine
        #token_format: 'access_token' ##  "Permission 'iam.serviceAccounts.getAccessToken' denied on resource (or it may not exist).",
        ## https://console.cloud.google.com/iam-admin/workload-identity-pools
        ## https://github.com/orgs/community/discussions/139154
        ## https://gist.github.com/brokedba/b473ce5812f582e164da55d787c3d588
        ## https://cloud.google.com/iam/docs/workload-identity-federation-with-deployment-pipelines#create_the_workload_identity_pool_and_provider
        ## https://console.cloud.google.com/iam-admin/workload-identity-pools/pool/undp-test-earth-engine-pool-id?project=undp-test-earth-engine
        ## https://github.com/google-github-actions/auth (using gcloud)

    - run : ls -la 

    - uses: google-github-actions/setup-gcloud@v1

    - run: gcloud info

    - run: 'gcloud auth list --filter=status:ACTIVE --format="value(account)"'

    - run : gcloud services list --enabled 
      #continue-on-error: true 
        
    - name: Deploy to Cloud Functions
      ##  Cloud Functions API ?? 
      ## 
      #continue-on-error: true 
      run: |
        gcloud functions deploy flask-example \
          --entry-point main \
          --runtime python310 \
          --trigger-http \
          --allow-unauthenticated \
          --region us-central1
