name: deploy_a

on: 
  workflow_dispatch :

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name : Authentification1 
      run: |
        ## settings/secrets/actions 
        ## important!! replace 
        ## When configuring the json data, exchange " for \" 
        echo "${{ secrets.JSON }}" > credentials.json

        ## "...Cloud Resource Manager API has not been used in project XYZ before or it is disabled..." 
        ## -> " Cloud Resource Manager API -> Enable"
        gcloud auth activate-service-account --key-file="credentials.json"
        gcloud config set project ${{ secrets.PROJECT }}
        rm credentials.json

    - uses: 'google-github-actions/setup-gcloud@v2'

    - run: 'gcloud info'    
      
    - name: Checkout code
      uses: actions/checkout@v4 

    - name: Deploy to Cloud Functions
      run: |
        gcloud functions deploy flask-example \
          --entry-point main \
          --runtime python310 \
          --trigger-http \
          --allow-unauthenticated \
          --region us-central1
