name: deploy_a

on: 
  workflow_dispatch :

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy to Cloud Functions
      run: |
        gcloud functions deploy flask-example \
          --entry-point main \
          --runtime python310 \
          --trigger-http \
          --allow-unauthenticated \
          --region us-central1
